In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [6]:
df[["Name","Sex","Age"]]

                                                  Name     Sex   Age
0                              Braund, Mr. Owen Harris    male  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                               Heikkinen, Miss. Laina  female  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                             Allen, Mr. William Henry    male  35.0
..                                                 ...     ...   ...
886                              Montvila, Rev. Juozas    male  27.0
887                       Graham, Miss. Margaret Edith  female  19.0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN
889                              Behr, Mr. Karl Howell    male  26.0
890                                Dooley, Mr. Patrick    male  32.0

[891 rows x 3 columns]

In [7]:
df1 = df[["Name","Sex","Age"]][0:5]

In [8]:
df1

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0

In [9]:
df2 = df[["Name","Sex","Age"]][5:10]

In [10]:
df2

                                                Name     Sex   Age
5                                   Moran, Mr. James    male   NaN
6                            McCarthy, Mr. Timothy J    male  54.0
7                     Palsson, Master. Gosta Leonard    male   2.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0

# Concatenation can be done by two types:
1. Vertical Concatenation. (Axis = 0)
2. Horizontal Concatenation.(Axis = 1)

In [12]:
df1+df2 #This is wrong method for concatenation of dataframe.

  Name  Sex  Age
0  NaN  NaN  NaN
1  NaN  NaN  NaN
2  NaN  NaN  NaN
3  NaN  NaN  NaN
4  NaN  NaN  NaN
5  NaN  NaN  NaN
6  NaN  NaN  NaN
7  NaN  NaN  NaN
8  NaN  NaN  NaN
9  NaN  NaN  NaN

In [18]:
# Vertical COncatenation, by default axis = 0.
ver_df = pd.concat([df1, df2])

In [19]:
ver_df

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0
5                                   Moran, Mr. James    male   NaN
6                            McCarthy, Mr. Timothy J    male  54.0
7                     Palsson, Master. Gosta Leonard    male   2.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0

In [23]:
#Horizontal Concatenation >> We have to set axis = 1.
hor_df1 = pd.concat([df1, df2], axis = 1)

In [24]:
hor_df

,Name,Sex,Age,Name,Sex,Age
0,"Braund, Mr. Owen Harris",male,22.0,NaN,NaN,NaN
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,NaN,NaN,NaN
2,"Heikkinen, Miss. Laina",female,26.0,NaN,NaN,NaN
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,NaN,NaN,NaN
4,"Allen, Mr. William Henry",male,35.0,NaN,NaN,NaN
5,NaN,NaN,NaN,"Moran, Mr. James",male,NaN
6,NaN,NaN,NaN,"McCarthy, Mr. Timothy J",male,54.0
7,NaN,NaN,NaN,"Palsson, Master. Gosta Leonard",male,2.0
8,NaN,NaN,NaN,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0
9,NaN,NaN,NaN,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0

In [25]:
df2.reset_index(drop = True, inplace = True)

In [26]:
df2

                                                Name     Sex   Age
0                                   Moran, Mr. James    male   NaN
1                            McCarthy, Mr. Timothy J    male  54.0
2                     Palsson, Master. Gosta Leonard    male   2.0
3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0
4                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0

In [27]:
hor_df = pd.concat([df1, df2], axis = 1)

In [29]:
hor_df

,Name,Sex,Age,Name,Sex,Age
0,"Braund, Mr. Owen Harris",male,22.0,"Moran, Mr. James",male,NaN
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,"McCarthy, Mr. Timothy J",male,54.0
2,"Heikkinen, Miss. Laina",female,26.0,"Palsson, Master. Gosta Leonard",male,2.0
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0
4,"Allen, Mr. William Henry",male,35.0,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0

# Merging two data frames. It can be done in four ways- It is more like set operation like, A+B, B+A, Union Operation, Intersection Operation.
1. Left merge >> Where some part of the right data frame merge with left data frame to form a new data frame.
2. Right Merge >> where some part of the left data frame merge with right data frame to form a new data frame.
3. Outer Merge >> It is more like an Union operation of set.
4. Inner Merge >> It is more like an Intersection Operation of set.
5. Cross merge >> Every permutaion of rows thst sre there.

In [59]:
Adf = pd.DataFrame({
    'key1' : [1,2,4,5,6],
    'key2': [4,5,6,7,8],
    'key3' : [3,4,5,6,6]
})
Adf

   key1  key2  key3
0     1     4     3
1     2     5     4
2     4     6     5
3     5     7     6
4     6     8     6

In [67]:
Bdf = pd.DataFrame({
    'key1' : [1,2,45,6,67],
    'key4': [56,5,6,7,8],
    'key5' : [3,56,5,6,6]
})
Bdf

   key1  key4  key5
0     1    56     3
1     2     5    56
2    45     6     5
3     6     7     6
4    67     8     6

In [68]:
# Inner Merge
inn = pd.merge(Adf,Bdf, how = 'inner')

In [69]:
inn

   key1  key2  key3  key4  key5
0     1     4     3    56     3
1     2     5     4     5    56
2     6     8     6     7     6

In [70]:
pd.merge(Adf,Bdf, how = 'left')

   key1  key2  key3  key4  key5
0     1     4     3  56.0   3.0
1     2     5     4   5.0  56.0
2     4     6     5   NaN   NaN
3     5     7     6   NaN   NaN
4     6     8     6   7.0   6.0

In [71]:
pd.merge(Adf,Bdf, how = 'right')

   key1  key2  key3  key4  key5
0     1   4.0   3.0    56     3
1     2   5.0   4.0     5    56
2    45   NaN   NaN     6     5
3     6   8.0   6.0     7     6
4    67   NaN   NaN     8     6

In [72]:
pd.merge(Adf,Bdf, how = 'outer')

   key1  key2  key3  key4  key5
0     1   4.0   3.0  56.0   3.0
1     2   5.0   4.0   5.0  56.0
2     4   6.0   5.0   NaN   NaN
3     5   7.0   6.0   NaN   NaN
4     6   8.0   6.0   7.0   6.0
5    45   NaN   NaN   6.0   5.0
6    67   NaN   NaN   8.0   6.0

In [73]:
pd.merge(Adf,Bdf, how = 'cross')

    key1_x  key2  key3  key1_y  key4  key5
0        1     4     3       1    56     3
1        1     4     3       2     5    56
2        1     4     3      45     6     5
3        1     4     3       6     7     6
4        1     4     3      67     8     6
5        2     5     4       1    56     3
6        2     5     4       2     5    56
7        2     5     4      45     6     5
8        2     5     4       6     7     6
9        2     5     4      67     8     6
10       4     6     5       1    56     3
11       4     6     5       2     5    56
12       4     6     5      45     6     5
13       4     6     5       6     7     6
14       4     6     5      67     8     6
15       5     7     6       1    56     3
16       5     7     6       2     5    56
17       5     7     6      45     6     5
18       5     7     6       6     7     6
19       5     7     6      67     8     6
20       6     8     6       1    56     3
21       6     8     6       2     5    56
22       6     8     6      45     6     5
23       6     8     6       6     7     6
24       6     8     6      67     8     6

In [75]:
# Join >> Join work based on index/ merge works based on columns.
df1 = pd.DataFrame({
    'key1' : [1,2,4,5,6],
    'key2': [4,5,6,7,8],
    'key3' : [3,4,5,6,6]},
    index = ['a', 'b', 'c', 'd', 'e']
                )
df1

   key1  key2  key3
a     1     4     3
b     2     5     4
c     4     6     5
d     5     7     6
e     6     8     6

In [77]:
# Join >> Join work based on index/ merge works based on columns.
df2 = pd.DataFrame({
    'key6' : [1,2,45,6,67],
    'key4': [56,5,6,7,8],
    'key5' : [3,56,5,6,6]},
    index = ['a', 'b', 'h', 'i', 'j']
                )
df2

   key6  key4  key5
a     1    56     3
b     2     5    56
h    45     6     5
i     6     7     6
j    67     8     6

In [78]:
df1.join(df2, how = 'inner')

   key1  key2  key3  key6  key4  key5
a     1     4     3     1    56     3
b     2     5     4     2     5    56

In [79]:
df1.join(df2, how = 'outer')

   key1  key2  key3  key6  key4  key5
a   1.0   4.0   3.0   1.0  56.0   3.0
b   2.0   5.0   4.0   2.0   5.0  56.0
c   4.0   6.0   5.0   NaN   NaN   NaN
d   5.0   7.0   6.0   NaN   NaN   NaN
e   6.0   8.0   6.0   NaN   NaN   NaN
h   NaN   NaN   NaN  45.0   6.0   5.0
i   NaN   NaN   NaN   6.0   7.0   6.0
j   NaN   NaN   NaN  67.0   8.0   6.0

In [80]:
df1.join(df2, how = 'left')

   key1  key2  key3  key6  key4  key5
a     1     4     3   1.0  56.0   3.0
b     2     5     4   2.0   5.0  56.0
c     4     6     5   NaN   NaN   NaN
d     5     7     6   NaN   NaN   NaN
e     6     8     6   NaN   NaN   NaN

In [81]:
df1.join(df2, how = 'right')

   key1  key2  key3  key6  key4  key5
a   1.0   4.0   3.0     1    56     3
b   2.0   5.0   4.0     2     5    56
h   NaN   NaN   NaN    45     6     5
i   NaN   NaN   NaN     6     7     6
j   NaN   NaN   NaN    67     8     6

In [82]:
df1.join(df2, how = 'cross')

    key1  key2  key3  key6  key4  key5
0      1     4     3     1    56     3
1      1     4     3     2     5    56
2      1     4     3    45     6     5
3      1     4     3     6     7     6
4      1     4     3    67     8     6
5      2     5     4     1    56     3
6      2     5     4     2     5    56
7      2     5     4    45     6     5
8      2     5     4     6     7     6
9      2     5     4    67     8     6
10     4     6     5     1    56     3
11     4     6     5     2     5    56
12     4     6     5    45     6     5
13     4     6     5     6     7     6
14     4     6     5    67     8     6
15     5     7     6     1    56     3
16     5     7     6     2     5    56
17     5     7     6    45     6     5
18     5     7     6     6     7     6
19     5     7     6    67     8     6
20     6     8     6     1    56     3
21     6     8     6     2     5    56
22     6     8     6    45     6     5
23     6     8     6     6     7     6
24     6     8     6    67     8     6

In [83]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [84]:
# apply function >> to apply a function on all the values of the columns
df["Fare"]

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [86]:
df["Fare_INR"] = df["Fare"].apply(lambda x : x*90)

In [87]:
df["Fare_INR"]

0       652.500
1      6415.497
2       713.250
3      4779.000
4       724.500
         ...
886    1170.000
887    2700.000
888    2110.500
889    2700.000
890     697.500
Name: Fare_INR, Length: 891, dtype: float64

In [88]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_INR
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,652.500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,6415.497
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,713.250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4779.000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,724.500
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1170.000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,2700.000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,2110.500
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,2700.000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,697.500

In [89]:
df["Name_len"] = df["Name"].apply(len)

In [90]:
df["Name_len"]

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name_len, Length: 891, dtype: int64

In [91]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_INR,Name_len
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,652.500,23
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,6415.497,51
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,713.250,22
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4779.000,44
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,724.500,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1170.000,21
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,2700.000,28
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,2110.500,40
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,2700.000,21
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,697.500,19

In [92]:
#Apply User defined function >>
def convert(x):
    return x*90

In [94]:
df["user_fun"] = df["Fare"].apply(convert)

In [95]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_INR,Name_len,user_fun
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,652.500,23,652.500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,6415.497,51,6415.497
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,713.250,22,713.250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4779.000,44,4779.000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,724.500,24,724.500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1170.000,21,1170.000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,2700.000,28,2700.000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,2110.500,40,2110.500
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,2700.000,21,2700.000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,697.500,19,697.500

In [98]:
def create_flag(x):
    if(x<10):
        return "Low Fare"
    elif((10<x)&(x<20)):
        return "Medium Fare"
    else:
        return "High Fare"

In [99]:
df["Flag"] = df["Fare"].apply(create_flag)

In [100]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_INR,Name_len,user_fun,Flag
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,652.500,23,652.500,Low Fare
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,6415.497,51,6415.497,High Fare
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,713.250,22,713.250,Low Fare
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4779.000,44,4779.000,High Fare
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,724.500,24,724.500,Low Fare
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1170.000,21,1170.000,Medium Fare
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,2700.000,28,2700.000,High Fare
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,2110.500,40,2110.500,High Fare
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,2700.000,21,2700.000,High Fare
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,697.500,19,697.500,Low Fare

In [101]:
# Join >> Join work based on index/ merge works based on columns.
df2 = pd.DataFrame({
    'a' : [1,2,3,4],
    'b': [5,5,6,7],
    'c' : ['pw','skills','av','nn']
})
df2

   a  b       c
0  1  5      pw
1  2  5  skills
2  3  6      av
3  4  7      nn

In [103]:
df2.set_index('c', inplace = True)

In [104]:
df2

        a  b
c
pw      1  5
skills  2  5
av      3  6
nn      4  7

In [105]:
df2.reset_index(drop = True, inplace = True)

In [106]:
df2

   a  b
0  1  5
1  2  5
2  3  6
3  4  7

In [109]:
df2.reindex([1,2,3,0])

   a  b
1  2  5
2  3  6
3  4  7
0  1  5

In [112]:
for i in df2.iterrows():
    print(i, "....")

(0, a    1
b    5
Name: 0, dtype: int64) ....
(1, a    2
b    5
Name: 1, dtype: int64) ....
(2, a    3
b    6
Name: 2, dtype: int64) ....
(3, a    4
b    7
Name: 3, dtype: int64) ....

In [114]:
for i in df2.items():
    print(i)

('a', 0    1
1    2
2    3
3    4
Name: a, dtype: int64)
('b', 0    5
1    5
2    6
3    7
Name: b, dtype: int64)

In [115]:
def func_sum(x):
    return x.sum()

In [116]:
df2.apply(func_sum)

a    10
b    23
dtype: int64

In [117]:
df2.apply(func_sum, axis = 1)

0     6
1     7
2     9
3    11
dtype: int64

In [119]:
df2.map(lambda x:x**2)

    a   b
0   1  25
1   4  25
2   9  36
3  16  49

In [120]:
df1

   key1  key2  key3
a     1     4     3
b     2     5     4
c     4     6     5
d     5     7     6
e     6     8     6

In [121]:
df2 = pd.DataFrame({
    'key6' : [1,2,45,6,67],
    'key4': [56,5,6,7,8],
    'key5' : [3,56,5,6,6]}
                )
df2

   key6  key4  key5
0     1    56     3
1     2     5    56
2    45     6     5
3     6     7     6
4    67     8     6

In [123]:
df2.sort_values(by = 'key6')

   key6  key4  key5
0     1    56     3
1     2     5    56
3     6     7     6
2    45     6     5
4    67     8     6

In [124]:
df2.sort_values(by = 'key4')

   key6  key4  key5
1     2     5    56
2    45     6     5
3     6     7     6
4    67     8     6
0     1    56     3